"""
SpectralQ Contracts Module.
Exports frozen schema definitions and non-coercive validation functions.
"""

from spectralq.contracts.schemas import (
    CURRENT_SCHEMA_VERSION,
    SourceMode,
    FsSource,
    DecoderStatus,
    CrcStatus,
    LadderLevel,
    EvidenceStatus,
    EpistemicState,
    BurstRecord,
    ParameterEstimate,
    EstimatesBlock,
    CumulantsBlock,
    ClusterBlock,
    FeaturesBlock,
    AnalysisContract,
    DecoderOutputContract,
    ClassifierOutputContract,
    TruthContract,
    HypothesisItem,
    AlternateHypothesisItem,
    EvidenceItem,
    ProvenanceBlock,
    ResultContract,
    validate_analysis_dict,
    validate_decoder_output_dict,
    validate_classifier_output_dict,
    validate_truth_dict,
    validate_result_dict,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "SourceMode",
    "FsSource",
    "DecoderStatus",
    "CrcStatus",
    "LadderLevel",
    "EvidenceStatus",
    "EpistemicState",
    "BurstRecord",
    "ParameterEstimate",
    "EstimatesBlock",
    "CumulantsBlock",
    "ClusterBlock",
    "FeaturesBlock",
    "AnalysisContract",
    "DecoderOutputContract",
    "ClassifierOutputContract",
    "TruthContract",
    "HypothesisItem",
    "AlternateHypothesisItem",
    "EvidenceItem",
    "ProvenanceBlock",
    "ResultContract",
    "validate_analysis_dict",
    "validate_decoder_output_dict",
    "validate_classifier_output_dict",
    "validate_truth_dict",
    "validate_result_dict",
]
