"""
spectralq.schemas

Typed schemas, dataclasses, and enums for Phase 3:
- Bitstream analysis results
- Hypothesis representation
- Evidence items and ledger
- Contradiction records
- Deterministic confidence components
- Machine-readable handoff contract for downstream aggregation (Archit / GUI)

PRODUCTION TRUTH ISOLATION:
This module contains zero references to ground-truth files, test fixtures,
or official case labels.
"""

from __future__ import annotations
from dataclasses import dataclass, field, asdict
from enum import Enum
from typing import Dict, Any, List, Optional, Union
import json
import numpy as np


class EvidenceCategory(str, Enum):
    """Categories of factual evidence produced across the demod/decode pipeline."""
    PHYSICAL_SIGNAL = "PHYSICAL_SIGNAL"
    TIMING = "TIMING"
    CARRIER = "CARRIER"
    DEMODULATION = "DEMODULATION"
    MAPPING = "MAPPING"
    PHASE = "PHASE"
    INTERLEAVER = "INTERLEAVER"
    FEC = "FEC"
    REENCODE = "REENCODE"
    BITSTREAM_STRUCTURE = "BITSTREAM_STRUCTURE"
    REFERENCE = "REFERENCE"
    REFERENCE_AVAILABILITY = "REFERENCE_AVAILABILITY"


class ContradictionSeverity(str, Enum):
    """Severity levels for contradictory or anomalous evidence."""
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class HypothesisStatus(str, Enum):
    """Evaluation status of a specific pipeline or parameter hypothesis."""
    CONFIRMED_BY_MULTIPLE_EVIDENCE = "CONFIRMED_BY_MULTIPLE_EVIDENCE"
    SUPPORTED = "SUPPORTED"
    TENTATIVE = "TENTATIVE"
    AMBIGUOUS = "AMBIGUOUS"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    REJECTED = "REJECTED"


class StructuralClassification(str, Enum):
    """Deterministic structural classifications of recovered bitstreams."""
    TEXT_LIKE = "TEXT_LIKE"
    BYTE_STRUCTURED = "BYTE_STRUCTURED"
    HIGHLY_REPETITIVE = "HIGHLY_REPETITIVE"
    BINARY_STRUCTURED = "BINARY_STRUCTURED"
    PADDING_OR_CONSTANT = "PADDING_OR_CONSTANT"
    UNKNOWN_STRUCTURE = "UNKNOWN_STRUCTURE"


class EvidenceReliability(str, Enum):
    """Reliability weight tiers for evidence items."""
    HIGH = "HIGH"          # Deterministic algebraic check (e.g. CRC, re-encode match)
    MEDIUM = "MEDIUM"      # Statistical/estimator metric (e.g. timing variance, EVM)
    LOW = "LOW"            # Heuristic or short-burst estimation
    UNAVAILABLE = "UNAVAILABLE"


@dataclass
class BitstreamAnalysisResult:
    """Deterministic structural and statistical analysis of a bitstream.

    Contains NO semantic guessing or fabricated payloads.
    """
    # A. Length
    bit_count: int
    byte_count: int
    is_byte_aligned: bool
    remainder_bits: int

    # B. Basic Bit Statistics
    zero_count: int
    one_count: int
    one_density: float
    empirical_entropy: float  # Shannon entropy in bits/bit (0.0 to 1.0)

    # C. Run-length Structure
    max_zero_run: int
    max_one_run: int
    mean_run_length: float
    total_runs: int
    run_length_distribution: Dict[int, int] = field(default_factory=dict)

    # D. Periodicity / Repetition
    detected_period: Optional[int] = None
    max_autocorrelation_peak: float = 0.0
    has_periodic_framing: bool = False
    autocorrelation_peaks: List[Dict[str, Any]] = field(default_factory=list)
    repeated_blocks: List[Dict[str, Any]] = field(default_factory=list)

    # E. Byte Structure (over aligned byte span)
    aligned_byte_count: int = 0
    unique_byte_count: int = 0
    printable_ascii_ratio: float = 0.0
    ascii_control_ratio: float = 0.0
    zero_byte_ratio: float = 0.0
    high_bit_set_ratio: float = 0.0
    byte_entropy: float = 0.0  # Shannon entropy in bits/byte (0.0 to 8.0)
    top_byte_frequencies: List[Dict[str, Any]] = field(default_factory=list)

    # F. Structural Signatures
    structural_classification: StructuralClassification = StructuralClassification.UNKNOWN_STRUCTURE
    classification_justification: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to JSON-serializable dictionary."""
        d = asdict(self)
        d["structural_classification"] = self.structural_classification.value
        return d


@dataclass
class EvidenceItem:
    """An atomic, auditable item of evidence generated by the decoder subsystem."""
    evidence_id: str
    category: EvidenceCategory
    metric: str
    value: Any
    unit: str
    source: str
    reliability: EvidenceReliability
    interpretation: str
    supports: List[str] = field(default_factory=list)
    contradicts: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "evidence_id": self.evidence_id,
            "category": self.category.value if isinstance(self.category, EvidenceCategory) else str(self.category),
            "metric": self.metric,
            "value": self._sanitize_value(self.value),
            "unit": self.unit,
            "source": self.source,
            "reliability": self.reliability.value if isinstance(self.reliability, EvidenceReliability) else str(self.reliability),
            "interpretation": self.interpretation,
            "supports": list(self.supports),
            "contradicts": list(self.contradicts),
        }

    @staticmethod
    def _sanitize_value(val: Any) -> Any:
        if isinstance(val, (np.integer, int)):
            return int(val)
        if isinstance(val, (np.floating, float)):
            if np.isnan(val) or np.isinf(val):
                return None
            return float(val)
        if isinstance(val, (np.bool_, bool)):
            return bool(val)
        if isinstance(val, np.ndarray):
            return val.tolist()
        return val


@dataclass
class Contradiction:
    """Explicitly recorded contradictory or anomalous evidence."""
    contradiction_id: str
    contradiction_type: str
    severity: ContradictionSeverity
    details: str
    metric: str
    value: Any
    source_evidence_ids: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "contradiction_id": self.contradiction_id,
            "contradiction_type": self.contradiction_type,
            "severity": self.severity.value if isinstance(self.severity, ContradictionSeverity) else str(self.severity),
            "details": self.details,
            "metric": self.metric,
            "value": EvidenceItem._sanitize_value(self.value),
            "source_evidence_ids": list(self.source_evidence_ids),
        }


@dataclass
class Hypothesis:
    """Generic hypothesis evaluated by the candidate engine."""
    hypothesis_id: str
    category: str
    parameters: Dict[str, Any]
    status: HypothesisStatus
    evidence_refs: List[str] = field(default_factory=list)
    score_components: Dict[str, float] = field(default_factory=dict)
    contradictions: List[str] = field(default_factory=list)
    re_encode_errors: Optional[int] = None
    consistency_fraction: Optional[float] = None
    rank: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "hypothesis_id": self.hypothesis_id,
            "category": self.category,
            "parameters": self.parameters,
            "status": self.status.value if isinstance(self.status, HypothesisStatus) else str(self.status),
            "evidence_refs": list(self.evidence_refs),
            "score_components": {k: float(v) for k, v in self.score_components.items()},
            "contradictions": list(self.contradictions),
            "re_encode_errors": self.re_encode_errors,
            "consistency_fraction": float(self.consistency_fraction) if self.consistency_fraction is not None else None,
            "rank": int(self.rank),
        }


@dataclass
class ConfidenceComponent:
    """Deterministic contribution to overall evidence confidence."""
    name: str
    raw_metric: Any
    normalized_score: float  # 0.0 to 1.0
    weight: float           # Contribution weight
    reason: str
    source_evidence_ids: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "raw_metric": EvidenceItem._sanitize_value(self.raw_metric),
            "normalized_score": round(float(self.normalized_score), 4),
            "weight": round(float(self.weight), 4),
            "reason": self.reason,
            "source_evidence_ids": list(self.source_evidence_ids),
        }


@dataclass
class ConfidenceResult:
    """Deterministic, transparent evidence confidence summary."""
    value: Optional[float]  # 0.0 to 1.0, or None if completely unassessable
    method: str
    method_version: str
    components: Dict[str, ConfidenceComponent] = field(default_factory=dict)
    penalties: Dict[str, float] = field(default_factory=dict)
    uncertainty_reasons: List[str] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "value": round(float(self.value), 4) if self.value is not None else None,
            "method": self.method,
            "method_version": self.method_version,
            "components": {k: v.to_dict() for k, v in self.components.items()},
            "penalties": {k: round(float(v), 4) for k, v in self.penalties.items()},
            "uncertainty_reasons": list(self.uncertainty_reasons),
        }


@dataclass
class DecoderEvidenceHandoff:
    """Stable, machine-readable handoff object for Archit's downstream aggregator."""
    schema_version: str
    case_id: str
    decoder: Dict[str, Any]
    candidate_hypotheses: List[Hypothesis] = field(default_factory=list)
    selected_hypothesis: Optional[Hypothesis] = None
    bitstream_analysis: Optional[BitstreamAnalysisResult] = None
    evidence: List[EvidenceItem] = field(default_factory=list)
    contradictions: List[Contradiction] = field(default_factory=list)
    confidence: Optional[ConfidenceResult] = None
    reference: Dict[str, Any] = field(default_factory=dict)
    uncertainty_reasons: List[str] = field(default_factory=list)
    overall_status: str = "UNKNOWN"
    provenance: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "schema_version": self.schema_version,
            "case_id": self.case_id,
            "overall_status": self.overall_status,
            "decoder": self.decoder,
            "candidate_hypotheses": [h.to_dict() for h in self.candidate_hypotheses],
            "selected_hypothesis": self.selected_hypothesis.to_dict() if self.selected_hypothesis else None,
            "bitstream_analysis": self.bitstream_analysis.to_dict() if self.bitstream_analysis else None,
            "evidence": [e.to_dict() for e in self.evidence],
            "contradictions": [c.to_dict() for c in self.contradictions],
            "confidence": self.confidence.to_dict() if self.confidence else None,
            "reference": self.reference,
            "uncertainty_reasons": list(self.uncertainty_reasons),
            "provenance": self.provenance,
        }

    def to_json(self, indent: int = 2) -> str:
        """Serialize to a deterministic JSON string."""
        return json.dumps(self.to_dict(), indent=indent, sort_keys=False)
